<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DaklaPack.Shipments.Application\DaklaPack.Shipments.Application.csproj" />
    <ProjectReference Include="..\DaklaPack.Shipments.Infrastructure\DaklaPack.Shipments.Infrastructure.csproj" />
  </ItemGroup>

</Project>
